# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_curso',
                'doc_host': 'https://JuanDiaz12000.github.io',
                'git_url': 'https://github.com/JuanDiaz12000/nbdev_curso',
                'lib_path': 'nbdev_curso'},
  'syms': {'nbdev_curso.core': {'nbdev_curso.core.foo': ('core.html#foo', 'nbdev_curso/core.py')}}}
